version: '3'
services:
  mysql:
    image: mysql:8
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"
    networks:
      - mynetwork
    volumes:
      - mysql-data:/var/lib/mysql

  redis:
    image: redis:5
    container_name: redis-container
    ports:
      - "6379:6379"
    networks:
      - mynetwork
    volumes:
      - redis-data:/data

networks:
  mynetwork:
    driver: bridge

volumes:
  mysql-data:
    driver: local
  redis-data:
    driver: local
